@isTest
private without sharing class CourseRegistrationEmailHelperTest {
	@isTest
	private static void testFetchOrCreateContacts() {

		Test.StartTest();
		// CourseRegistrationEmailHelper.fetchOrCreateContacts();
		Test.StopTest();
	}

	@isTest
	private static void testCreateCourseRegistrations() {

		Test.StartTest();
		// CourseRegistrationEmailHelper.createCourseRegistrations();
		Test.StopTest();
	}
}