#!/bin/bash

# Oppretter scratch org
sf org create scratch --definition-file config/project-scratch-def.json --alias $1 --duration-days $2 --set-default --json --wait 30

# Installer platform-data-model ver. 0.1.47
sf package install --package 04tQC000001C7efYAC --no-prompt --wait 30 --publish-wait 30

# Installer custom-metadata-dao ver. 0.1.47
sf package install --package 04tQC000001C7bRYAS --no-prompt --wait 30 --publish-wait 30

# Installer custom-permission-helper ver. 0.1.47
sf package install --package 04tQC000001C7d3YAC --no-prompt --wait 30 --publish-wait 30

# Installer feature-toggle ver. 0.1.48
sf package install --package 04tQC000001C7jVYAS --no-prompt --wait 30 --publish-wait 30

# Installerer crm-platform-base ver. 0.305
sf package install --package 04tQC000001JMgzYAG --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-platform-access-control ver. 0.177
sf package install --package 04tQC000001AGR7YAO --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-platform-reporting ver. 0.41 
sf package install --package 04tKB000000YAWDYA4 --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-shared-base ver. 1.1
sf package install --package 04t2o000000ySqpAAE --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-thread-view ver. 0.6
sf package install --package 04tKB000000YEDVYA4 --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-shared-timeline ver. 1.32
sf package install --package 04tQC000000kTYTYA2 --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-shared-flowComponents ver. 0.4 
sf package install --package 04t7U0000008qz4QAA --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installer crm-henvendelse-base ver. 0.36
sf package install --package 04tQC000000uSXtYAM --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-platform-integration ver. 0.155 
sf package install --package 04tQC000000lBhZYAU --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-shared-user-notification ver. 0.27 
sf package install --package 04tQC0000012h6jYAA --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-journal-utilities ver. 0.43
sf package install --package 04tKB000000Y9WtYAK --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-platform-oppgave ver. 0.64
sf package install --package 04tKB000000YB09YAG --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-arbeidsgiver-base ver. 1.691
sf package install --package 04tQC000001LJ77YAG --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-community-base ver. 0.144
sf package install --package 04tQC000001KZx7YAG --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-platform-email-scheduling ver. 1.7
sf package install --package 04t7U000000Y2bXQAS --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Installerer crm-hot-felles ver. 0.14 
sf package install --package 04tQC000001LQ29YAG --no-prompt --installation-key $3 --wait 30 --publish-wait 30

# Dytter kildekoden til scratch org'en
sf project deploy start

# Tildeler tilatelsessett til brukeren
sf org assign permset --name Kurs_Salesforce_Admin

# Tildeler tilatelsessett til brukeren 
sf org assign permset --name Course_Admin

# Publish Experience Site
sf community publish --name Kurs

# Kjører assignGuestUserPerm.sh…
bash "$(dirname "$0")/assignGuestUserPerm.sh"

#Trenger dette for at course registration skal fungere.
# Oppretter EncryptionKey
sf data create record \
  --sobject EncryptionKey__c \
  --values "Name='encryptionKey' Value__c='FkU94SvM4cn0jBhYXkgb9dLuFSh3+qtoVWmuW/0elB8='"
