name: "[PUSH] Create Package"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "force-app/**"
jobs:
  create-package:
    name: Run Package Creation
    uses: navikt/crm-workflows-base/.github/workflows/packageCreate.yml@master
    permissions:
      contents: write
    secrets: inherit

  install-in-preprod:
    name: Deploy package
    needs: [create-package]
    uses: navikt/crm-workflows-base/.github/workflows/deployPackage.yml@master
    permissions:
      contents: read
    with:
      packageId: ${{ needs.create-package.outputs.packageId }}
      org: preprod
      unpackagable: ./force-app/unpackagable-with-auto-deploy
    secrets: inherit
