# Unique name for this workflow
name: "[Push] Deploy to Dev Sandbox"

# Definition when the workflow should run
on:
  push:
    branches:
      - dev
    paths:
      - "force-app/**"

# Jobs to be executed
jobs:
  deploy-metadata:
    name: Create new package
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: "Install Salesforce CLI" # TODO implement https://github.com/marketplace/actions/salesforce-sfdx-cli-action
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v2

      # Store secret for package target org installation
      - name: "Populate auth file with DEV_SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.DEV_SFDX_URL}} > ./DEV_SFDX_URL.txt"

      # Authenticate dev sandbox
      - name: "Authenticate dev sandbox"
        run: "sfdx force:auth:sfdxurl:store -f ./DEV_SFDX_URL.txt -a dev -s"

      # Remove auth files
      - name: "Remove auth files"
        if: always()
        run: |
          rm -f ./DEV_SFDX_URL.txt

      # Delete unpackagable
      - name: "Delete unpackagable"
        run: rm -rf unpackagable

      # Install sfpowerkit plugin used to install multiple packages only by version number
      - name: "Install sfpowerkit plugin"
        run: "echo y | sfdx plugins:install sfpowerkit"

      # Install packages this repo is dependant on
      - name: "Install dependant packages"
        run: "sfdx sfpowerkit:package:dependencies:install -u dev -r -a -w 60 -k '${{ secrets.ALL_PACKAGE_KEYS }}'"

      # Install new package version into dev sandbox
      - name: "Install new package version into dev sandbox"
        if: success()
        id: dev-installation
        run: |
          sfdx force:source:deploy -p force-app -u dev
