name: "[PUSH] Create Package"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "force-app/**"
jobs:
  create-package:
    name: Run Package Creation
    uses: navikt/crm-workflows-base/.github/workflows/packageCreate.yml@master
    permissions:
      contents: write
    secrets: inherit

  install-in-org:
    name: Deploy package to ${{ matrix.org }}
    needs: [create-package]
    uses: navikt/crm-workflows-base/.github/workflows/deployPackage.yml@master
    strategy:
      matrix:
        org: [preprod, uat]
    permissions:
      contents: read
    with:
      packageId: ${{ needs.create-package.outputs.packageId }}
      org: ${{ matrix.org }}
      unpackagable: ./force-app/unpackagable-with-auto-deploy
    secrets: inherit
